name: Build WebDriverAgent
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout WebDriverAgent
        uses: actions/checkout@v4
        with:
          repository: appium/WebDriverAgent
          path: WebDriverAgent
      - name: Build WDA
        run: |
          cd WebDriverAgent
          xcodebuild build-for-testing -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'generic/platform=iOS' -derivedDataPath ./build CODE_SIGNING_ALLOWED=NO
      - name: Zip Payload
        run: |
          cd WebDriverAgent/build/Build/Products/Debug-iphoneos
          mkdir Payload
          cp -r WebDriverAgentRunner-Runner.app Payload/
          zip -r WDA.ipa Payload
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WDA-ipa
          path: WebDriverAgent/build/Build/Products/Debug-iphoneos/WDA.ipa
